[IMP] core: allow to hide debug info on exception
When running Odoo in a production server we don't need to show extra
debuggin info on every exception. This is especially sensitive for
unauthenticated endpoints that could leak internal info about the local
paths in the system.

Before, a simple error in a parameter of an endpoint leads to a full
disclosure of traceback info:
```
>>> pprint(requests.get("http://localhost:8069/test",data=json.dumps({"params":{"id":5}}),headers={"content-type": "application/json"}).json(),width=130)
{'error': {'code': 200,
           'data': {'arguments': ["Request.stop() missing 1 required positional argument: 'token'"],
                    'context': {},
                    'debug': 'Traceback (most recent call last):\n'
                             '  File "/home/odoo/src/odoo/17.0/odoo/http.py", line 1726, in _serve_db\n'
                             '    return service_model.retrying(self._serve_ir_http, self.env)\n'
                             '  File "/home/odoo/src/odoo/17.0/odoo/service/model.py", line 133, in retrying\n'
                             '    result = func()\n'
                             '  File "/home/odoo/src/odoo/17.0/odoo/http.py", line 1753, in _serve_ir_http\n'
                             '    response = self.dispatcher.dispatch(rule.endpoint, args)\n'
                             '  File "/home/odoo/src/odoo/17.0/odoo/http.py", line 1957, in dispatch\n'
                             "    result = self.request.registry['ir.http']._dispatch(endpoint)\n"
                             '  File "/home/odoo/src/odoo/17.0/odoo/addons/base/models/ir_http.py", line 222, in _dispatch\n'
                             '    result = endpoint(**request.params)\n'
                             '  File "/home/odoo/src/odoo/17.0/odoo/http.py", line 726, in route_wrapper\n'
                             '    result = endpoint(self, *args, **params_ok)\n'
                             "TypeError: Request.stop() missing 1 required positional argument: 'token'\n",
                    'message': "Request.stop() missing 1 required positional argument: 'token'",
                    'name': 'builtins.TypeError'},
           'message': 'Odoo Server Error'},
 'id': None,
 'jsonrpc': '2.0'}
```

After, with the config set to anything distinct from `debug` the extra
debugging info is disabled:
```
>>> pprint(requests.get("http://localhost:8069/test",data=json.dumps({"params":{"id":5}}),headers={"content-type": "application/json"}).json(),width=130)
{'error': {'code': 200,
           'data': {'message': "Request.stop() missing 1 required positional argument: 'token'"},
           'message': 'Odoo Server Error'},
 'id': None,
 'jsonrpc': '2.0'}
```