[FIX] purchase,sale: fix NoneType has no attribute action_share
AttributeError: 'NoneType' object has no attribute 'action_share'
This error occurs when the customer tries to click on the share action.
steps to produce:
1) Create a new record for 'sale.order'.
2) Go to the 'web_studio' menu and modify the 'customer' field to be not
   required and save the changes.
3) After making the changes, click on the action button and select the share
   option. At this point, the error occurs.

After applying this commit will fix this issue.

sentry - 4190581897