[FIX] webiste, website_sale : resolve issues caused by converting jQuery
Removed unnecessary code from zooOdoo.js

Introduced compensateScrollbar method , this method was for a jquery
element now a compatible method for html el has been made in web/utils.

Resolved and updated code according to coding standards
UncaughtPromiseError > TypeError
Uncaught Promise > element?.matches is not a function
TypeError: element?.matches is not a function

zoomOdoo on hover traceback
UncaughtClientError > TypeError
Uncaught Javascript Error > jQueryimage[0]?.zoomOdoo is not a function
TypeError: jQueryimage[0]?.zoomOdoo is not a function

snippet_animation ->
UncaughtClientError > TypeError
Uncaught Javascript Error > Failed to execute 'removeEventListener' on
'EventTarget': 2 arguments required, but only 1 present.

task-3929643