[FIX] account_edi_ubl: Cannot confirm invoice
Steps to reproduce the bug:
- Install Belgian accounting
- Switch to the Belgian company
- Activate Sales -> Settings -> Pricing -> Discounts
- Create a sale order with a discount
- Confirm the sale order
- Add the delivered quantity
- Click "Create Invoice" and then "Create and View Invoice"
- Confirm the invoice

Bug:
Traceback:

Error to render compiling AST
TypeError: 'NoneType' object is not callable
Template: account_edi_ubl.export_ubl_invoice_line
Path: /t/cac:InvoiceLine/cbc:Note

opw:2355296

closes odoo/odoo#59433

Signed-off-by: Nicolas Martinelli (nim) <nim@odoo.com>