[IMP] core: unify treatment of addons paths between config and CLI
- don't hard-error when a `--addons-path` is invalid
- add a warning when an addon path is invalid, whether from a config
  file or the command-line , warning is ported over from the CLI
  error: an addon path must be a directory which contains at least one
  directory which contains a manifest file... this may be way too
  restrictive for our needs (maybe just check if it's a directory
  which exists?)
- remove defaulting when no addons paths are provided (via either
  config or CLI), `initialize_sys_path` always adds
  `$root_path/addons` if it's missing so doing that twice seems
  unnecessary, and it looks like the modules which should generally
  do init properly, so...