[FIX] base{,_import_module},mail: prevent upload corrupt image file
Currently, there are the following errors that occur when users upload
corrupt image (or a svg image file by changing the extension to jpeg):
- Exceptioan was occurred at upload file in website with follow steps
    1. Install a website.
    2. Go to the website and enable edit mode
    3. Select any image and try to replace it with a corrupt image
    4. Traceback will appear
- In mail, when the user tries to upload a corrupt image in activity or with
  mail, it does not upload the image, and it also doesn't show any process
  to the user; it just shows the progress bar and nothing to be upload. 

`Error: AttributeError: 'bool' object has no attribute 'size'`

This commit solves the above issue by following:
- Throwing a user error when img.image was False at [1] or
  Unidentified ImageError at the time of processing the image .
- In mail, it shows an error message to the user's when an  user error occurs.
- Apart from this, the commit also renames variable `_` as `__` because the `_`
  variable is used for translation in Odoo and also adapt the test cases.

[1]-https://github.com/odoo/odoo/blob/b98d0ad9f8dc4a6e4bd0112bc9f060b0671f3e8e/odoo/addons/base/models/ir_attachment.py#L335
[2]-https://github.com/odoo/odoo/blob/b98d0ad9f8dc4a6e4bd0112bc9f060b0671f3e8e/odoo/tools/image.py#L78-L80

sentry-4402006108