[FIX] gamification: added inherit in file
At [1], we are using the 'message_notify' method in the 'goal.py' file but
forgot to inherit from 'mail.thread', where this method is defined.

Traceback: AttributeError
'gamification.goal' object has no attribute 'message_notify'

This commit will fix the above error by adding the necessary inheritance in the
file.

[1]- https://github.com/odoo/odoo/blob/718bc95bd3bdbac1603310dafc054936935364e2/addons/gamification/models/goal.py#L224

sentry-5634399280